---
type: object
required: [name, appspec]
properties:
  name: { type: string }
  appspec:
    type: object
    required: [version]
    properties:
      version: { type: number }
  title: { type: string }
  abstract: { type: string }
  description: { type: string }
  options:
    '$ref': '#/definitions/options'
  subcommands:
    type: object
    patternProperties:
      "^[a-zA-Z0-9_]+$":
        '$ref': '#/definitions/command'
definitions:
  optionTypeSimple:
    enum: [bool, string]
  optionTypeEnum:
    type: object
    properties:
      enum:
        type: array
  options:
    type: array
    items:
      '$ref': '#/definitions/option'
  option:
    type: object
    properties:
      name: { type: string }
      description: { type: string }
      type:
        oneOf:
          - '$ref': '#/definitions/optionTypeSimple'
          - '$ref': '#/definitions/optionTypeEnum'
      aliases:
        type: array
        items: { type: string }
  command:
    type: object
    properties:
      summary: { type: string }
      op: { type: string }
      parameters:
        type: array
        properties:
          name: { type: string }
          required: { type: bool }
          type:
            type: object
      options:
        '$ref': '#/definitions/options'

