---
name: appspec
appspec: { version: 0.001 }
title: Utilities for spec files for App::Spec cli apps
markup: swim
description: |
  This script is a collection of tools for authors of [App::Spec] command line
  scripts.
options:
  - name: color
    summary: output colorized
    type: flag
    aliases: [C]
subcommands:
  completion:
    summary: Generate completion for a specified spec file
    description: |
      This command takes a spec file and outputs the corresponding
      shell script for tab completion.
    op: cmd_completion
    options:
    - name: name
      description: name of the program
    - name: zsh
      description: for zsh
      type: flag
    - name: bash
      description: for bash
      type: flag
    parameters:
    - &param_spec_file
      name: spec_file
      type: file
      required: true
      summary: Path to the spec file (use '-' for standard input)
  pod:
    summary: Generate pod
    description: |
      This command takes a spec file and outputs the generated pod
      documentation.
    op: generate_pod
    parameters:
    - *param_spec_file
  validate:
    summary: Validate spec file
    description: |
      This command takes a spec file and validates it against the current
      [App::Spec] schema.
    op: validate
    parameters:
    - *param_spec_file
# vim:et:sts=2:sws=2:sw=2:foldmethod=indent
