name: Create GHCR Docker Container(s)

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
     - 'v*' # Push events to matching v*, i.e v1.0, v20.15.10 etc
     - 'latest'

jobs:
  # Build contianer
  build_container:
    name: Build Container
    runs-on: ubuntu-latest
    steps:
      # Standard checkout step
      - name: Checkout code
        id: git_checkout
        uses: actions/checkout@v3
      # Use qemu to perform multiplatform builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      # Use docker buildx to build multi-platform containers
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          use: true
          install: true
          config-inline: |
            [worker.oci]
              max-parallelism = 2
      # Log in to GitHub Container registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # Build and push docker images
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./
          platforms: linux/amd64
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
